Repository younginch/subtitle, pull requests merged in 2022-06, with the labels that each got.

#6 Fix bug on srt parse
  src/subtitles/__tests__/srt.test.ts
  src/subtitles/subtitle.ts
Labels: bug

#8 Fix cd public dist
  .github/workflows/cd.yml
  .npmignore
  README.md
  package-lock.json
  package.json
  tsconfig.json
Labels: bug

#11 Add SRTFile, SRTContent exports
  README.md
  package-lock.json
  package.json
  src/index.ts
  src/subtitles/SRTContent.ts
  src/subtitles/SRTFile.ts
  src/subtitles/SubContent.ts
  src/subtitles/Subtitle.ts
  src/subtitles/__tests__/srt.test.ts
  src/subtitles/__tests__/utils.test.ts
  src/subtitles/srt.ts
  src/subtitles/subComponent.ts
  src/subtitles/subtitle.ts
  src/subtitles/vtt.ts
  src/utils.ts
Labels: bug, enhancement

#12 Update cd.yml
  .github/workflows/cd.yml
  package.json
Labels: cicd
